# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/double.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto_files/double.proto\"&\n\ndoubleSend\x12\x18\n\x10\x64ouble_data_send\x18\x01 \x01(\x01\"&\n\ndoubleRecv\x12\x18\n\x10\x64ouble_data_recv\x18\x01 \x01(\x01\x32\x36\n\ndoubleTest\x12(\n\x0c\x64oubleReturn\x12\x0b.doubleSend\x1a\x0b.doubleRecvb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_files.double_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DOUBLESEND._serialized_start=28
  _DOUBLESEND._serialized_end=66
  _DOUBLERECV._serialized_start=68
  _DOUBLERECV._serialized_end=106
  _DOUBLETEST._serialized_start=108
  _DOUBLETEST._serialized_end=162
# @@protoc_insertion_point(module_scope)
