# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/float.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto_files/float.proto\"$\n\tfloatSend\x12\x17\n\x0f\x66loat_data_send\x18\x01 \x01(\x02\"$\n\tfloatRecv\x12\x17\n\x0f\x66loat_data_recv\x18\x01 \x01(\x02\x32\x32\n\tfloatTest\x12%\n\x0b\x66loatReturn\x12\n.floatSend\x1a\n.floatRecvb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_files.float_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLOATSEND._serialized_start=27
  _FLOATSEND._serialized_end=63
  _FLOATRECV._serialized_start=65
  _FLOATRECV._serialized_end=101
  _FLOATTEST._serialized_start=103
  _FLOATTEST._serialized_end=153
# @@protoc_insertion_point(module_scope)
