# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/int32.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto_files/int32.proto\"$\n\tint32Send\x12\x17\n\x0fint32_data_send\x18\x01 \x01(\x05\"$\n\tint32Recv\x12\x17\n\x0fint32_data_recv\x18\x01 \x01(\x05\x32\x32\n\tint32Test\x12%\n\x0bint32Return\x12\n.int32Send\x1a\n.int32Recvb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_files.int32_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INT32SEND._serialized_start=27
  _INT32SEND._serialized_end=63
  _INT32RECV._serialized_start=65
  _INT32RECV._serialized_end=101
  _INT32TEST._serialized_start=103
  _INT32TEST._serialized_end=153
# @@protoc_insertion_point(module_scope)
