# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/string.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto_files/string.proto\"&\n\nstringSend\x12\x18\n\x10string_data_send\x18\x01 \x01(\t\"&\n\nstringRecv\x12\x18\n\x10string_data_recv\x18\x01 \x01(\t26\n\nstringTest\x12(\n\x0cstringReturn\x12\x0b.stringSend\x1a\x0b.stringRecvb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_files.string_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRINGSEND._serialized_start=28
  _STRINGSEND._serialized_end=66
  _STRINGRECV._serialized_start=68
  _STRINGRECV._serialized_end=106
  _STRINGTEST._serialized_start=108
  _STRINGTEST._serialized_end=162
# @@protoc_insertion_point(module_scope)
